USE muvidb_db;
ALTER TABLE movie ADD pub_date TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER summary;
ALTER IGNORE TABLE Countries ADD UNIQUE INDEX(`code`);
ALTER IGNORE TABLE movie ADD UNIQUE INDEX(`imdbid`);
ALTER IGNORE TABLE Languages ADD UNIQUE INDEX(`code`);
##SELECT name, count(id) as cnt FROM Countries  GROUP BY code HAVING cnt > 1;
